### ISSUE TITLE
Already forked

### ISSUE THREAD

**Issue by jeerbl** [pankajpatel/fontgen-loader#5]
Hello,
I already forked this at https://github.com/jeerbl/webfonts-loader, maybe we could unite forces.

Cheers
Jerome

**Comment by pankajpatel** [comment]
That would be great! Where should we move it?

I kept the same name because it will be easy to find who are facing issues while implementing the repo.

**Comment by pankajpatel** [comment]
I think we should move it under an organization.

Problem is that both of our forks are in use right now. Mine is in less usage. 

@IlyaSemenov contributed to it as well.

If we can come up with some good place to move it, it will be good.

I suggest for [github.com/dwyl](https://github.com/dwyl).

**Comment by jeerbl** [comment]
Yes I know but the loader name had to change on the npm repository. I created [`webfonts-loader`](https://www.npmjs.com/package/webfonts-loader) on npm so that people know it is different. I started refactoring the code on my repo and I already included WOFF2 generation support.

Do you want me to add you as a collaborator on my repo? And then we close this one. No need for both of them.

If you don't want to collaborate I can handle it myself, as you wish ;)

**Comment by jeerbl** [comment]
Ok just saw your second comment, yes indeed we can mive it there. I didn't know dwyl but if you think it is a good solution then I'll move it there during the week.

**Comment by pankajpatel** [comment]
Well @nelsonic from @dwyl can suggest on this. 

You can checkout the org repos, I am ok with both options.

**Comment by pankajpatel** [comment]
@jeerbl can you please check if your version completely shadows ours?

I would suggest that we keep the name same to original one, because we are obviously carrying forward original repo. 

We will post a issue in the original repo saying the newest fork and the ways it can be utilized.

**Comment by jeerbl** [comment]
@pankajpatel I disagree on keeping the same name as I don't want people looking for this repo to see the old one on Google and anywhere else as it is not being updated. I added something in the README about the previous not updated repo.

About the code, I can actually keep it on my Github and add you as collaborator if you are ready to collaborate on further updates.

**Comment by jeerbl** [comment]
By the way, still about the name, I want the name of the Github repo to be the same as on npm.

**Comment by pankajpatel** [comment]
@jeerbl alright. your wish. I will redirect all from this repo to yours.

**Comment by jeerbl** [comment]
I tried this repo and mine seems to completely shadow yours.
